# SPDX-FileCopyrightText: 2021-2022 Carnegie Mellon University
# SPDX-License-Identifier: MIT
---
- name: set up firewall
  block:
  - name: firewall - allow ssh access
    community.general.ufw:
      rule: allow
      port: ssh
      proto: tcp
  - name: firewall - enable
    community.general.ufw:
      state: enabled
      policy: deny
  when: enable_ufw

- name: install package updates
  apt:
    update_cache: yes
    upgrade: yes

# ansible kubernetes depends on some non-stdlib python modules
- name: install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: install dependencies for ansible.kubernetes
  ansible.builtin.pip:
    executable: pip3
    name: openshift
    state: present
